config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  get '/auth/facebook/callback', to: "api/sessions#omniauth_facebook"
  get '/auth/google_oauth2/callback', to: "api/sessions#omniauth_google"

  resources :users
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:index, :show, :create, :update]
    resource :session, only: [:create, :destroy, :show]
    resources :languages, except: [:new, :edit]
    resources :courses, except: [:new, :edit] do
      resources :skills, except: [:new, :edit, :create, :show]
    end
    resources :skills, only: [:create, :show, :destroy, :update] do
      resources :lessons, except: [:new, :edit, :create, :show]
    end
    resources :lessons, only: [:create, :show, :destroy, :update] do
      resources :exercises, only: [:create, :index, :destroy, :update]
    end
    resources :exercises, only: [:show]
    resources :course_enrollments, only: [:create]
    resources :completions, only: [:create]
  end
end

app/views/layouts/_guest_signin_button.html.erb
<form action="<%= session_url %>" method="post">
  <%= auth_token_input %>

  <div class="guest-inputs">

    <input type="hidden"
           name="session[username]"
           value="guest">

    <input type="hidden"
           name="session[password]"
           value="password">

    <button>Log in as guest</button>
  </div>
</form>

app/views/layouts/_login_form.html.erb
<div class="splash-login-form splash-form">
  <div class="up-triangle">
  </div>
  <div class="splash-login-inputs">
  <form action="<%= session_url %>" method="post">
    <%= auth_token_input %>

      <input name="session[username]"
             placeholder="Username">

      <input type="password"
             name="session[password]"
             placeholder="Password">

      <button class="splash-login-button">Log in</button>
  </form>

  <%= render "layouts/guest_signin_button" %>

  <form class="signup-button" action="<%= new_user_url %>" method="get">
    <button>Not a member yet?</button>
  </form>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linguana</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link
    href='https://fonts.googleapis.com/css?family=Montserrat+Alternates:400,700'
    rel='stylesheet'
    type='text/css'>
  <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>

<%= yield %>

</body>
</html>